/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loja;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 * 
 */
public class CadastroCliente extends javax.swing.JFrame {
    
    private List<Cliente> cliente;
    private Iterator it;
    private int indice;

    /**
     * Creates new form LojaApp
     */
    public CadastroCliente() {
        initComponents();
        cliente = new ArrayList();
        it = cliente.iterator();
    } 
    public CadastroCliente(List<Cliente> cliente) {
        initComponents();
        this.cliente = cliente;
        it = cliente.iterator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNomeLabel = new javax.swing.JLabel();
        jEnderecoLabel = new javax.swing.JLabel();
        jCpfLabel = new javax.swing.JLabel();
        jEmailLabel = new javax.swing.JLabel();
        jNomeText = new javax.swing.JTextField();
        jCPFText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jEnderecoText = new javax.swing.JTextField();
        jFinalizaButton = new javax.swing.JButton();
        jLimpaTelaButton = new javax.swing.JButton();
        jCriarContaButton = new javax.swing.JButton();
        jExcluirContaButton = new javax.swing.JButton();
        jEditarButton = new javax.swing.JButton();
        jConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO CLIENTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LOJA DE PRODUTOS ELETRÔNICOS");

        jNomeLabel.setText("Nome :");

        jEnderecoLabel.setText("Endereço :");

        jCpfLabel.setText("CPF :");

        jEmailLabel.setText("E-Mail :");

        jCPFText.setMaximumSize(new java.awt.Dimension(258, 258));
        jCPFText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPFTextActionPerformed(evt);
            }
        });

        jFinalizaButton.setText("Finalizar");
        jFinalizaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalizaButtonActionPerformed(evt);
            }
        });

        jLimpaTelaButton.setText("Limpar Tela");
        jLimpaTelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpaTelaButtonActionPerformed(evt);
            }
        });

        jCriarContaButton.setText("Criar Conta");
        jCriarContaButton.setToolTipText("");
        jCriarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriarContaButtonActionPerformed(evt);
            }
        });

        jExcluirContaButton.setText("Excluir Conta");
        jExcluirContaButton.setToolTipText("");
        jExcluirContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirContaButtonActionPerformed(evt);
            }
        });

        jEditarButton.setText("Editar");
        jEditarButton.setToolTipText("");
        jEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarButtonActionPerformed(evt);
            }
        });

        jConsulta.setText("Consultar");
        jConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jExcluirContaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jEnderecoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEnderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jEmailLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jCpfLabel)
                                        .addGap(19, 19, 19)
                                        .addComponent(jCPFText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNomeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLimpaTelaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCriarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jEditarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 42, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFinalizaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNomeLabel)
                    .addComponent(jNomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCpfLabel)
                    .addComponent(jCPFText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailLabel)
                    .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEnderecoLabel)
                    .addComponent(jEnderecoText))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLimpaTelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEditarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConsulta))
                .addGap(133, 133, 133)
                .addComponent(jExcluirContaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCriarContaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFinalizaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFinalizaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalizaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jFinalizaButtonActionPerformed

    private void jLimpaTelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpaTelaButtonActionPerformed
        // TODO add your handling code here:
        limpar_tela();
        
    }//GEN-LAST:event_jLimpaTelaButtonActionPerformed

    private void jCriarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriarContaButtonActionPerformed
        // TODO add your handling code here:
        String nome=jNomeText.getText();
        String cpf=jCPFText.getText();
        String email=jEmailText.getText();
        String endereco=jEnderecoText.getText();
        criar(nome,cpf,email,endereco);
        
        limpar_tela();
        
    }//GEN-LAST:event_jCriarContaButtonActionPerformed

    private void jExcluirContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirContaButtonActionPerformed
        // TODO add your handling code here:
            if(JOptionPane.showConfirmDialog(null, "Você realmente deseja excluir a conta?","Processo de Exclusão",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==0)
            excluir();
            
    }//GEN-LAST:event_jExcluirContaButtonActionPerformed

    private void jEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarButtonActionPerformed
        // TODO add your handling code here:
        if(indice!=0){
            editar(indice-1);
            JOptionPane.showMessageDialog(this, "Cliente editado com sucesso!");
            limpar_tela();
        } else {
            JOptionPane.showMessageDialog(null,"Lista Vazia!");
    }
        
    }//GEN-LAST:event_jEditarButtonActionPerformed

    private void jCPFTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPFTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPFTextActionPerformed

    private void jConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaActionPerformed
        // TODO add your handling code here:
        if(!it.hasNext()){
            it=cliente.iterator();
            indice=0;
        }
        
        salvar_tela((Cliente) it.next());
        indice++;
        
    }//GEN-LAST:event_jConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCPFText;
    private javax.swing.JButton jConsulta;
    private javax.swing.JLabel jCpfLabel;
    private javax.swing.JButton jCriarContaButton;
    private javax.swing.JButton jEditarButton;
    private javax.swing.JLabel jEmailLabel;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jEnderecoLabel;
    private javax.swing.JTextField jEnderecoText;
    private javax.swing.JButton jExcluirContaButton;
    private javax.swing.JButton jFinalizaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLimpaTelaButton;
    private javax.swing.JLabel jNomeLabel;
    private javax.swing.JTextField jNomeText;
    // End of variables declaration//GEN-END:variables
    private void criar(String nome, String cpf, String email, String endereco) {

    for (Cliente c : cliente) {
        if (c.getNome().equals (nome)|| c.getCpf().equals(cpf) || c.getEmail().equals(email)) {
            JOptionPane.showMessageDialog(this, "Já existe um cliente com o mesmo Nome, CPF ou Email!");
            return;
        }
    }
    Cliente criaCliente = new Cliente(nome, cpf, email, endereco);
    cliente.add(criaCliente);
    it = cliente.iterator();
    JOptionPane.showMessageDialog(this, "Cliente criado com sucesso!");
    }

    
    private void excluir(){
        
        it.remove();
        it=cliente.iterator();
        limpar_tela();
  
    }
 
    private void editar(int ponto){
        Cliente criaCliente;
        String nome=jNomeText.getText();
        String cpf=jCPFText.getText();
        String email=jEmailText.getText();
        String endereco=jEnderecoText.getText();
        criaCliente = new Cliente(nome,cpf,email,endereco);
        cliente.set(ponto, criaCliente);
          
    }

    private void limpar_tela(){

    jNomeText.setText("");
    jCPFText.setText("");
    jEmailText.setText("");
    jEnderecoText.setText("");
    it=cliente.iterator();
    indice=0;
    
    }
    
    private void salvar_tela(Cliente clienteSalvar){
        
    jNomeText.setText(clienteSalvar.getNome());
    jCPFText.setText(clienteSalvar.getCpf());
    jEmailText.setText(clienteSalvar.getEmail());
    jEnderecoText.setText(clienteSalvar.getEndereco());
    
    }
    
}

    
    
    
