/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loja;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class CadastroProduto extends javax.swing.JFrame {
    
    private List<Produto> produtos;
    private Iterator<Produto> it;
    private int indice;
    private int indiceAtual = -1;
    private double preco = 0.0;
    private int estoque = 0;
    private TelaVenda telaVenda;
    private Map<String, Integer> estoqueDefinidoProduto = new HashMap<>();

    /**
     * Creates new form NewJFrame
     */
    public CadastroProduto() {
        initComponents();
        produtos = new ArrayList<>();
        it = produtos.iterator();
        
    }
    
    public CadastroProduto(List<Produto> produtos) {
        initComponents();
        this.produtos = produtos;
        it = produtos.iterator();
       
    }
    
    public CadastroProduto(TelaVenda telaVenda) {
        this.telaVenda = telaVenda;
        initComponents();
        produtos = new ArrayList<>();
        it = produtos.iterator();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jNomeProdutoLabel = new javax.swing.JLabel();
        jPrecoProdutoLabel = new javax.swing.JLabel();
        jQuantidadeLabel = new javax.swing.JLabel();
        jTipoProdutoLabel = new javax.swing.JLabel();
        jTipoProdutoText = new javax.swing.JTextField();
        jNomeProdutoText = new javax.swing.JTextField();
        jPrecoProdutoText = new javax.swing.JTextField();
        jQuantidadeProdutoText = new javax.swing.JTextField();
        jCriarProdutoButton = new javax.swing.JButton();
        jExcluirProdutoButton = new javax.swing.JButton();
        jEditarProdutoButton = new javax.swing.JButton();
        jFinalizar = new javax.swing.JButton();
        jTitulo = new javax.swing.JLabel();
        jCadastroProdutoTituloLabel = new javax.swing.JLabel();
        jLimparTela = new javax.swing.JButton();
        jConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNomeProdutoLabel.setText("Nome do Produto:");

        jPrecoProdutoLabel.setText("Preço do Produto:");

        jQuantidadeLabel.setText("Quantidade do Produto:");

        jTipoProdutoLabel.setText("Tipo do Produto:");

        jCriarProdutoButton.setText("Criar");
        jCriarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriarProdutoButtonActionPerformed(evt);
            }
        });

        jExcluirProdutoButton.setText("Excluir");
        jExcluirProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirProdutoButtonActionPerformed(evt);
            }
        });

        jEditarProdutoButton.setText("Editar");
        jEditarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarProdutoButtonActionPerformed(evt);
            }
        });

        jFinalizar.setText("Finalizar");
        jFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalizarActionPerformed(evt);
            }
        });

        jTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTitulo.setText("LOJA DE PRODUTOS ELETRÔNICOS");

        jCadastroProdutoTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCadastroProdutoTituloLabel.setText("CADASTRO PRODUTO");

        jLimparTela.setText("Limpar Tela");
        jLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparTelaActionPerformed(evt);
            }
        });

        jConsulta.setText("Consulta");
        jConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCriarProdutoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jExcluirProdutoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEditarProdutoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jQuantidadeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jQuantidadeProdutoText))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jPrecoProdutoLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPrecoProdutoText))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jNomeProdutoLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jNomeProdutoText))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTipoProdutoLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTipoProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLimparTela)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jCadastroProdutoTituloLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCadastroProdutoTituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTipoProdutoLabel)
                    .addComponent(jTipoProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeProdutoLabel)
                    .addComponent(jNomeProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrecoProdutoLabel)
                    .addComponent(jPrecoProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuantidadeLabel)
                    .addComponent(jQuantidadeProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLimparTela)
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCriarProdutoButton)
                        .addComponent(jExcluirProdutoButton)
                        .addComponent(jFinalizar)
                        .addComponent(jEditarProdutoButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCriarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriarProdutoButtonActionPerformed
        // TODO add your handling code here:
        String tipo = jTipoProdutoText.getText();
        String nome = jNomeProdutoText.getText();
        
        try {
            double preco = Double.parseDouble(jPrecoProdutoText.getText());
            int quantidade = Integer.parseInt(jQuantidadeProdutoText.getText());

            criar(tipo, nome, preco, quantidade);
            int estoqueInicial = Integer.parseInt(jQuantidadeProdutoText.getText());
            estoqueDefinidoProduto.put(nome, estoqueInicial);
            limpar_tela();
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor válido para o preço e a quantidade.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jCriarProdutoButtonActionPerformed

    private void jFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalizarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jFinalizarActionPerformed

    private void jExcluirProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirProdutoButtonActionPerformed
        // TODO add your handling code here:
        excluir();
        limpar_tela();
        
    }//GEN-LAST:event_jExcluirProdutoButtonActionPerformed

    private void jEditarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarProdutoButtonActionPerformed
        // TODO add your handling code here:
        String tipo = jTipoProdutoText.getText();
        String nome = jNomeProdutoText.getText();
        double preco = Double.parseDouble(jPrecoProdutoText.getText());
        int quantidade = Integer.parseInt(jQuantidadeProdutoText.getText());
        editar(tipo, nome, preco, quantidade);
        
    }//GEN-LAST:event_jEditarProdutoButtonActionPerformed

    private void jLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimparTelaActionPerformed
        // TODO add your handling code here:
        limpar_tela();
        
    }//GEN-LAST:event_jLimparTelaActionPerformed

    private void jConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaActionPerformed
        // TODO add your handling code here:
        if (!produtos.isEmpty()) {
            indiceAtual = (indiceAtual + 1) % produtos.size();
            Produto produtoAtual = produtos.get(indiceAtual);
            salvar_tela(produtoAtual);
        }
        
    }//GEN-LAST:event_jConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jCadastroProdutoTituloLabel;
    private javax.swing.JButton jConsulta;
    private javax.swing.JButton jCriarProdutoButton;
    private javax.swing.JButton jEditarProdutoButton;
    private javax.swing.JButton jExcluirProdutoButton;
    private javax.swing.JButton jFinalizar;
    private javax.swing.JButton jLimparTela;
    private javax.swing.JLabel jNomeProdutoLabel;
    private javax.swing.JTextField jNomeProdutoText;
    private javax.swing.JLabel jPrecoProdutoLabel;
    private javax.swing.JTextField jPrecoProdutoText;
    private javax.swing.JLabel jQuantidadeLabel;
    private javax.swing.JTextField jQuantidadeProdutoText;
    private javax.swing.JLabel jTipoProdutoLabel;
    private javax.swing.JTextField jTipoProdutoText;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables

    private void criar(String tipo, String nome, double preco, int quantidade) {
    boolean produtoExistente = produtos.stream()
            .anyMatch(p -> p.getNomeProduto().equalsIgnoreCase(nome) && p.getTipo().equalsIgnoreCase(tipo));
    
    if (produtoExistente) {
        JOptionPane.showMessageDialog(this, "Já existe um produto cadastrado com o mesmo nome deste, tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
    } else {
        Produto novoProduto = new Produto(tipo, nome, quantidade);
        novoProduto.setTipo(tipo);
        novoProduto.setNomeProduto(nome);
        novoProduto.setPreco(preco);
        novoProduto.setEstoque(quantidade);
        produtos.add(novoProduto);
        JOptionPane.showMessageDialog(this, "Produto criado com sucesso!");
    }
    
    }
    
    private void excluir() {
        if (indiceAtual != -1 && indiceAtual < produtos.size()) {
            produtos.remove(indiceAtual);
            limpar_tela();
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para excluir.");
    }
        
    }
    
    private void editar(String tipo, String nome, double preco, int quantidade) {
        
        if (indiceAtual != -1 && indiceAtual < produtos.size()) {
            Produto produtoAtual = produtos.get(indiceAtual);
            produtoAtual.setTipo(tipo);
            produtoAtual.setNomeProduto(nome);
            produtoAtual.setPreco(preco);
            produtoAtual.setEstoque(quantidade);
            JOptionPane.showMessageDialog(this, "Produto editado com sucesso!");
            limpar_tela();
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para editar.");
    }
        
    }

    private void salvar_tela(Produto produtoSalvar) {
        
    jTipoProdutoText.setText(produtoSalvar.getTipo());
    jNomeProdutoText.setText(produtoSalvar.getNomeProduto());
    jPrecoProdutoText.setText(Double.toString(produtoSalvar.getPreco()));
    jQuantidadeProdutoText.setText(Integer.toString(produtoSalvar.getEstoque()));
    
    }
    
    private void limpar_tela(){

    jTipoProdutoText.setText("");
    jNomeProdutoText.setText("");
    jPrecoProdutoText.setText("");
    jQuantidadeProdutoText.setText("");
    it=produtos.iterator();
    indice=0;
    
    }
    
    

}