/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loja;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class TelaSistema extends javax.swing.JFrame {

    /**
     * Creates new form TelaSistema
     */
    public TelaSistema() {
        initComponents();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastrosMenu = new javax.swing.JMenu();
        jClienteItem = new javax.swing.JMenuItem();
        jProdutoItem = new javax.swing.JMenuItem();
        jVendaMenu = new javax.swing.JMenu();
        jTelaVenda = new javax.swing.JRadioButtonMenuItem();
        jSairMenu = new javax.swing.JMenu();
        jSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOJA DE PRODUTOS ELETRONICOS");

        jCadastrosMenu.setText("Cadastrar");

        jClienteItem.setText("Cliente");
        jClienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteItemActionPerformed(evt);
            }
        });
        jCadastrosMenu.add(jClienteItem);

        jProdutoItem.setText("Produto");
        jProdutoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutoItemActionPerformed(evt);
            }
        });
        jCadastrosMenu.add(jProdutoItem);

        jMenuBar1.add(jCadastrosMenu);

        jVendaMenu.setText("Venda");
        jVendaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVendaMenuActionPerformed(evt);
            }
        });

        jTelaVenda.setSelected(true);
        jTelaVenda.setText("Tela Venda");
        jTelaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelaVendaActionPerformed(evt);
            }
        });
        jVendaMenu.add(jTelaVenda);

        jMenuBar1.add(jVendaMenu);

        jSairMenu.setText("Sair");

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jSairMenu.add(jSair);

        jMenuBar1.add(jSairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteItemActionPerformed
        // TODO add your handling code here:
    if (cliente == null)
        cliente = new ArrayList<>();
    CadastroCliente telaCliente = new CadastroCliente(cliente);
    telaCliente.setVisible(true);

    }//GEN-LAST:event_jClienteItemActionPerformed

    private void jProdutoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutoItemActionPerformed
        // TODO add your handling code here:
    if (produtos == null)
        produtos = new ArrayList<>();
    CadastroProduto cadastroProduto = new CadastroProduto(produtos);
    cadastroProduto.setVisible(true);
    }//GEN-LAST:event_jProdutoItemActionPerformed

    private void jVendaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVendaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVendaMenuActionPerformed

    private void jTelaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelaVendaActionPerformed
        // TODO add your handling code here:
        if (cliente.isEmpty() || produtos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, cadastre clientes e produtos antes de iniciar uma venda.");
            return;
        }

        TelaVenda telaVenda = new TelaVenda(cliente, produtos);
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jTelaVendaActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_jSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSistema().setVisible(true);
            }
        });
    }
    
    private List <Cliente> cliente;
    private List <Produto> produtos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCadastrosMenu;
    private javax.swing.JMenuItem jClienteItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jProdutoItem;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenu jSairMenu;
    private javax.swing.JRadioButtonMenuItem jTelaVenda;
    private javax.swing.JMenu jVendaMenu;
    // End of variables declaration//GEN-END:variables


    private void sair(){
        int option = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0); // Encerra o programa
        }
        
    }
}